import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import React from 'react'
import vinally from '../public/images/vinally.png'
import vinallyTwo from '../public/images/vinallytwo.png'
import linkedin from '../public/images/linkedin.png'
import github from '../public/images/github.png'

export default function Home() {

  return (
    <>
      <Head>
        <title>Dylan West • Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/radialblur.png" />
      </Head>
      <main className={styles.main}>
        <div id={styles.header}>
          <h1 id={styles.name}>Dylan West<Image className={styles.image} alt='' src='/images/emoji.png' width={160} height={80}/></h1>
          <code id={styles.sub}>Front-End Web Developer</code>
          <h3 id={styles.location}><Image id={styles.worldimg} alt='' src='/images/earth.png' width={15} height={15}/> United States</h3>
        </div>
        <div id={styles.bio}>
          <div id={styles.bioleft}>
            <h3>Hello, my name is Dylan. I am a web developer that loves building <br/> <span><em>front-end web applications.</em></span></h3>
            <div id={styles.tech}>
              <h4>Current Tech Stack:</h4>
              <Image id={styles.react} alt='' src='/images/react.png' width={25} height={25}/>
              <h5 className={styles.tooltip} id={styles.reacttooltip}>React</h5>
              <Image id={styles.next} alt='' src='/images/next.png' width={25} height={25}/>
              <h5 className={styles.tooltip} id={styles.nexttooltip}>Next.js</h5>
              <Image id={styles.js} alt='' src='/images/js.png' width={25} height={25}/>
              <h5 className={styles.tooltip} id={styles.jstooltip}>JavaScript</h5>
              <Image id={styles.express} alt='' src='/images/express.png' width={25} height={25}/>
              <h5 className={styles.tooltip} id={styles.expresstooltip}>Express</h5>
              <Image id={styles.vsc} alt='' src='/images/vsc.png' width={25} height={25}/>
              <h5 className={styles.tooltip} id={styles.vsctooltip}>Visual Studio</h5>
              <Image id={styles.github} alt='' src='/images/github.png' width={40} height={40}/>
              <h5 className={styles.tooltip} id={styles.githubtooltip}>Github</h5>
            </div>
            <div id={styles.buttons}>
              <button onClick={() => window.open('/pdf/resume.pdf')}>View Resume</button>
              <button>Projects</button>
            </div>
          </div>
          <div id={styles.bioright}>
            <Image id={styles.pfp} src='/images/radialblur.png' alt='' width={400} height={400} />
          </div>
        </div>
        <div id={styles.break}>
        </div>
        <div id={styles.projects}>
          <div id={styles.projectsheader}>
            <h3>FEATURED WORKS</h3>
          </div>
          <div id={styles.projectcards}>
            <div id={styles.cardOne}>
              <div className={styles.cardTop}>
                <div className={styles.cardTopLeft}>
                  <div className={styles.cardTopLeftTitle}>
                    <h3>Vinally</h3>
                    <code>/dylanw422/shopapp</code>
                  </div>
                  <div className={styles.cardTopLeftButton}>
                    <button onClick={() => window.open('https://shopapp-five.vercel.app')}>View Project</button>
                  </div>
                </div>
                <div className={styles.cardTopRight}>
                  <div className={styles.cardDescription}>
                    <h3>Vinally is an e-commerce web application with add-to-cart and checkout functionality</h3>
                  </div>
                  <div className={styles.cardTech}>
                    <h3>Built With:</h3>
                    <h4>JavaScript, React, CSS</h4>
                  </div>
                </div>
              </div>
              <div className={styles.cardBottom}>
                <Image id={styles.vinallyone} alt='' src={vinally}/>
                <Image id={styles.vinallytwo} alt='' src={vinallyTwo}/>
              </div>
            </div>
            <div id={styles.cardTwo}>
              <div className={styles.cardTop}>
                <div className={styles.cardTopLeft}>
                  <div className={styles.cardTopLeftTitle}>
                    <h3>Prism</h3>
                    <code>/dylanw422/prism</code>
                  </div>
                  <div className={styles.cardTopLeftButton}>
                    <button onClick={() => window.open('https://prism-beta.vercel.app')}>View Project</button>
                  </div>
                </div>
                <div className={styles.cardTopRight}>
                  <div className={styles.cardDescription}>
                    <h3>Prism is a web-application for financial data. Data is fetched from several APIs including Finnhub, CoinGecko, and ApeWisdom. Explore stocks trending on Reddit</h3>
                  </div>
                  <div className={styles.cardTech}>
                    <h3>Built With:</h3>
                    <h4>JavaScript, Express, React, CSS</h4>
                  </div>
                </div>
              </div>
              <div className={styles.cardBottom}>
                <Image id={styles.vinallyone} alt='' src='/images/prismone.png' width={450} height={260}/>
                <Image id={styles.vinallytwo} alt='' src='/images/prismtwo.png' width={450} height={260}/>
              </div>
            </div>
            <div id={styles.cardThree}>
              <div className={styles.cardTop}>
                <div className={styles.cardTopLeft}>
                  <div className={styles.cardTopLeftTitle}>
                    <h3>SayDifferent</h3>
                    <code>/dylanw422/saydifferent</code>
                  </div>
                  <div className={styles.cardTopLeftButton}>
                    <button onClick={() => window.open('https://saydifferent.vercel.app')}>View Project</button>
                  </div>
                </div>
                <div className={styles.cardTopRight}>
                  <div className={styles.cardDescription}>
                    <h3>SayDifferent is a web-app and Chrome extension that uses the power of OpenAI as a thesauras for phrases and sentences.</h3>
                  </div>
                  <div className={styles.cardTech}>
                    <h3>Built With:</h3>
                    <h4>JavaScript, React, CSS, OpenAI, ChromeAPI</h4>
                  </div>
                </div>
              </div>
              <div className={styles.cardBottom}>
                <Image id={styles.vinallyone} alt='' src='/images/sayone.png' width={450} height={260}/>
                <Image id={styles.vinallytwo} alt='' src='/images/saytwo.png' width={450} height={260}/>
              </div>
            </div>
          </div>
        </div>
        <div id={styles.breaktwo}>
        </div>
        <div className={styles.contact}>
          <div id={styles.contactHeader}>
            <h1>Contact Me</h1>
          </div>
          <div id={styles.contactmessage}>
            <h3>If you like my work, please feel free to contact me anytime! 😁</h3>
            <code onClick={() => window.open('mailto:dylanwestdev@gmail.com?subject=Hello Dylan!')}>dylanwestdev@gmail.com</code>
            <div id={styles.social}>
            <Image id={styles.linkedin} className={styles.socialimages} alt='' src={linkedin} onClick={() => window.open('https://linkedin.com/in/dylanwestdev')}/>
            <Image id={styles.github} className={styles.socialimages} alt='' src={github} onClick={() => window.open('https://github.com/dylanw422')}/>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
